# This is the sample workflow file.
# Github actions are written in YAML (Yet another markup language)
# it's nothing but key and values pair.
# neing defined in 3 forms.
# key and value
  # Key : value
# Library/dictionary (on is becoming dictionary)
  #key:
  #  key1:value1
  #  key2:value2
#list
  #key
  # - key1:valuea
  #   key2:valueb
  # - key1:valuec
  #   key1:valued
name: first_job
on: 
    push:
      branches: 
        - main
jobs:
    first_job:
      runs-on: ubuntu-latest
      steps: 
        - name: execute single line 
          run: cat /etc/os-release
    running_script_from_code:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2 # checkout/clone the repository in the runner GITHUB_WORKSPACE
        - name: run script
          run: chmod 755 script.sh && ./script.sh
        - name: running multiple line
          run: |
            chmod 755 script.sh
            ./script.sh 
    installing_packeges:
      runs-on: ubuntu-latest
      steps:
        - name: installing awscli
          run: |
            sudo apt-get update -y
            sudo apt-get update -y awscli wget
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee
            /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update -y
            sudo apt-get install -y terraform
            terraform --version
            aws --version		 

